### PR TITLE
Fixes issues #2 and #4  as well as adds scale and scroll reset enhancements

### PR DESCRIPTION
**Pull request by yaugenka**

### CODE REVIEW

**Comment by Zardozz** [comment]
Thanks for trying this but this looks like my first attempt but when a click listener is added to a child element, this grabs all the motion events and then scaling and scrolling stops working. My fix for this has now been manually tested and is ready for me to submit so this pull request is not needed. (I've included awakening the scrollbars in to my commit as well)

**Comment by yaugenka** [comment]
> but when a click listener is added to a child element, this grabs all the motion events and then scaling and scrolling stops working

I wonder why it does not work for you.  I have an app with click listeners added to row headers and both scale and scroll work like a charm.

**Comment by Zardozz** [comment]
The Demo App has them now has them added to all cells including the main table.
I've just tried on my clone of your fork just having them in the row headers and scale and scroll work fin in the main table area but not when trying to scroll or scale in the row headers. So may be you did not notice because all the user input was in areas that did not have click listeners?

**Comment by yaugenka** [comment]
Yes, you are right.
Will you also add the reset methods into your commit?

**Comment by Zardozz** [comment]
I've not added the reset methods in the commit as they are just wrappers around the already public `calculatePanScale` method. I'm not quite at the point of wanting to design an "API" at the moment as things might change a lot, so I want to keep the public methods to a minimum. Any App can currently use `calculatePanScale` with the right values instead at the moment.

**Comment by yaugenka** [comment]
To use `calculatePanScale` one needs to know what it does under the hood, which is kind of hard to understand without looking into the source code.

**Comment by yaugenka** [comment]
It looks like `scaleFactor` needs to be public for `calculatePanScale` to work as reset scale method, as well as `panX` and `panY` for scroll reset.

**Comment by yaugenka** [comment]
With regards to adding `local` folder to gitignore, I guess you keep local files in the `local.properties` folder and are working on a Linux or Mac machine. I work on Windows and it doesn't let create that folder because there is a file with the same name in the project.

**Comment by Zardozz** [comment]
local.properties is a file for me on Windows.

**Comment by yaugenka** [comment]
Hm.. There are two entries in gitignore: `local.properties` and `/local.properties`  which made me think you are using this folder for your local stuff like like `keystore` file and I was looking for a folder with an alternative name.

**Comment by Zardozz** [comment]
One of them is probably redundant but were added most likely by Android Studio

`local.properties` should ignore `local.properties` in any directory

 `/local.properties` should ignore `local.properties` only in the root directory

**Pull request closed without merging**
